openapi: 3.0.0
info:
  description: API for the TeamPickr app
  version: '1.0.0'
  title: TeamPickr
  contact:
    email: david.saltares@gmail.com
  license:
    name: MIT
    url: 'https://github.com/dsaltares/teamfindr/blob/main/LICENSE'
paths:
  /auth/verify:
    get:
      summary: verifies that the session for the user is valid
      operationId: verifyUser
      responses:
        '200':
          description: authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifySuccessResponse'
        '401':
          description: the session for the user is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/logout:
    get:
      summary: logs the user out
      operationId: logOut
      responses:
        '301':
          description: redirect to the application

  /users/{userId}:
    patch:
      summary: patches a user
      operationId: patchUser
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: id of the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchUserRequest'
        description: Inventory item to add
      responses:
        '200':
          description: authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchUserResponse'
        '403':
          description: user not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: not authorized to update the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: the session for the user is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    VerifySuccessResponse:
      type: object
      required:
        - user
        - cookies
      properties:
        user:
          $ref: '#/components/schemas/User'
        cookies:
          $ref: '#/components/schemas/Cookies'
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    PatchUserRequest:
      type: object
      required:
        - user
      properties:
        user:
          type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            avatar:
              type: string
    PatchUserResponse:
      type: object
      required:
        - user
      properties:
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      required:
        - id
        - email
        - createdAt
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        avatar:
          type: string
    Cookies:
      type: object
      required:
        - session
        - session.sig
      properties:
        session:
          type: string
        session.sig:
          type: string
